import Head from 'next/head';
import Header from '../components/header';
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <div className="flex flex-col items-center w-screen h-screen bg-gray-600">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Component {...pageProps}/>
    </div>
  ) 
}

export default MyApp
