import Head from 'next/head'
import Header from '../components/header'
import Sidebar from '../components/sidebar'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
  <div className="h-screen">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header></Header>
    <div class="flex h-full">
        <Sidebar/>
        <Component {...pageProps} />
    </div>
    
  </div>) 
}

export default MyApp
